version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: munashe
      POSTGRES_PASSWORD: mukomana
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"

volumes:
  postgres_data:
