# Generated by Django 4.2.2 on 2024-04-07 14:24

from django.db import migrations, transaction
from tasks.models import Task

def change_archived_tasks(apps, schema_editor):
    with transaction.atomic():
        # Update status of archived tasks to "DONE"
        Task.objects.filter(status="ARCHIVED").update(status="DONE")


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        # Change status of archived tasks to "DONE"
        migrations.RunPython(change_archived_tasks)
    ]
